### PR TITLE
updated all Pin_Headers

### PR DESCRIPTION
**Pull request by Shackmeister**
parameters from:
http://katalog.we-online.de/em/datasheet/6130xx11121.pdf
http://katalog.we-online.de/em/datasheet/6130xx21121.pdf
http://katalog.we-online.de/em/datasheet/6130xx11021.pdf
http://katalog.we-online.de/em/datasheet/6130xx21021.pdf

http://katalog.we-online.de/em/datasheet/6200xx11121.pdf
http://katalog.we-online.de/em/datasheet/6200xx21121.pdf
http://www.mouser.com/ds/2/4/page_280-282-24683.pdf

https://cdn.harwin.com/pdfs/M50-393.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Huge effort @Shackmeister! I haven't pulled it down yet but does this add any new pin headers or just update existing ones?

**Comment by Shackmeister** [comment]
Only existing ones, things which has been corrected:
Dimensions (it's existing connectors) 
The script is spitting out KLC compliant connectors 
All the stuff discussed in the issue :)

**Comment by poeschlr** [comment]
Might it be possible to provide a few screenshots?
I would suggest for 01x01 (or 0x02) and 01x16 (angled and straight) and 02x01 (or 02x02) and 02x10 (angled and straight)
This way we should get a good idea how the footprints will look like. (Yes i know you already posted some of them in the issue but it would still be a good idea.)

For such cases i make a board that has a selection of footprints on them that i deem sufficient to showcase the edge-cases of the script.
example: Per series one with the lowest number of pins, one about in the middle and one with the maximum number of pins. Maybe one with a randomly generated pin count. 
(in this case maybe don't use the one with the maximum pin count but example the 16 pin variant.)
I used this technique to [showcase my phoenix connectors](https://github.com/KiCad/packages3D/pull/10) Yes i know this is a 3d parts PR but i did not have this idea when i originally submitted the footprints.

You can also use this pcb later on when you add your new 3d models to showcase how they look like. (I seem to remember it was your original intention to create 3d models using cadquerry for this connectors.)

**Comment by Shackmeister** [comment]
THT with one column
pinheaders
and a small freebie
pinheaders
Ill upload the rest in a little bit

**Comment by Shackmeister** [comment]
Dual Column THT:
dualrow
3D:
3ddualrow

**Comment by Shackmeister** [comment]
@poeschlr is the silkscreen lines too big?
silkscreen

**Comment by Shackmeister** [comment]
the SMD pinheaders:
smd
and the 3d view
smd_pinheader

**Comment by Ratfink** [comment]
It looks like there's been a regression, undoing the changes from #22.  The SMD dual-row headers' pads are too far apart and too small again.

**Comment by Shackmeister** [comment]
Thanks for pointing this out, I honestly haven't been very thourough with the SMD ones, ill fix it in an hour

**Comment by Shackmeister** [comment]
@Ratfink that was a bit more work than anticipated but it should be fixed now, can you please check it?

**Comment by Ratfink** [comment]
It looks like the pad sizes are correct now, but the two rows of pads are still too far apart in the 1.27 mm dual-row SMD headers.  #22 made their X-positions ±1.95 instead of ±2.585, which appears consistent with [the drawing](http://www.mouser.com/ds/2/181/M50-360R-1064294.pdf) referenced there.

**Comment by Shackmeister** [comment]
@Ratfink I have now updated the script to support independent pad sizes, spacing etc for single and dual row.. (and updated all the parameters accordingly) can you please have another look?

**Comment by Ratfink** [comment]
The center positions for the pads in the 1.27 mm dual-row SMD headers look right now, but their size is a bit too big (2.6 mm long instead of 2.4).  As for the other SMD headers, I don't really know what's right, as different manufacturers' footprints seem to vary more.

**Comment by Shackmeister** [comment]
@Ratfink should be fixed now :)

**Comment by Ratfink** [comment]
I agree, they look correct again. :D

**Comment by Shackmeister** [comment]
Yay :D @Rene_Poschl @SchrodingersGat can you please have a look at the footprints (as asked above, im wondering if the silkscreen is ok)

**Comment by poeschlr** [comment]
I would personally increase the silkscreen distance to copper. (I normally make sure i have a silkscreen clearance of 0.2 or 0.25mm)

In my scripts i normally introduce a parameter that controls that clearance. (If applicable.)
I then calculate the points of silkscreen lines/polylines by using this parameter. 
I ignore cases where you get in trouble by using "unreasonable" clearance settings. (In other words: I test only +/-0.1mm from my default value.) Otherwise the scripts would get way to complicated.
I'm also not very precise. For circular pads i use the bounding rectangle as an approximation. (If i feel particularly motivated i add some correction factor to get better results.)

**Comment by Shackmeister** [comment]
Sounds fair, Ill have a look at it later.. I have updated all the parameters for the THT footprints but is waiting for the 3D models to finish generating so I can test the fit, afterwards ill check out the clearance issue

**Comment by jkriege2** [comment]
If you base this on my old scripts ... there should be a pathon-file that sets these parameters (somewhere ... might be in the tools-subdir).

Best,
JAN

**Comment by jkriege2** [comment]
PS: There are also 3- and 4-row THT pinheaders (and possibly receptables) available ... should we include those too?

cu
JAN

**Comment by Shackmeister** [comment]
Sounds good Jan, if we should include these are not really up to me but I can probably fit them in

**Comment by poeschlr** [comment]
We can include the 3,4 row versions if you are willing to create them. I would put them into a separate pull request though. (This pull request fixes the old footprints, a different pull request adds stuff. Keeps it cleaner in opinion.)

I think if we include the footprints we would need the symbols for them as well. currently there are no conn_3x?? and conn_4x?? variants.

**Comment by Shackmeister** [comment]
I can make the footprints and 3D models but symbols would be up to somebody else

**Comment by Shackmeister** [comment]
quite a few special cases to take care of, so there is still a lot of work going on. Also I dont want it merged before Im 100% satisfied (quite alot of the generator has been rewritten)
I fixed the silkscreen alignment, so it now fits perfectly with the pad clearance both for the square and round pads
padalign

**Comment by Shackmeister** [comment]
more stuff added to the script (mainly to the angled)
when the body is moved into the pads it will change the layout to add small bumps in between (see image)
also the script automatically moves the pin 1 indicator out if there is a clearance issue
all in all it should be close to impossible to have silkscreen on pads or pad clearance :) 
when I have made the same things to the Straight pin headers I believe the pin headers should be ready for merge
pinheader_preview

**Comment by Shackmeister** [comment]
I believe the Angled connectors are finished but please feel free to check them out and give any kind of feedback :)

**Comment by SchrodingersGat** [comment]
@Shackmeister this looks great! A couple of small things:

# RefDes Clearance

On the 1.27mm connectors, the second RefDes on F.Fab gets lost:

screenshot from 2017-06-28 19-23-46

Reducing size to 0.5mm (with 0.1mm line width) looks a lot better for the smaller connector:

screenshot from 2017-06-28 19-23-53

# Fab layer complexity

The fab layer drawings are great, but I feel they are a tad over-complicated for the angled connectors? 
I'm not sure of the best way to tackle this, below is a **suggestion** but I'm not wedded to it.

screenshot from 2017-06-28 19-27-04

Thanks for the hard work - hopefully we can get this merged soon :)

**Comment by Shackmeister** [comment]
thanks :) this is actually a part of the KLC suggestion :P the suggested 10% text thickness looks really thin and odd to me, perhaps some other percentage would work better?
regarding the script Ill just make it calculate what size fits and go with that, this way it will also work for potential new sizes :)

Personally I dont think the Fab drawing is very complicated, currently it shows the actual body size which I suppose is what it should, but more suggestions are ofcourse welcome :)

**Comment by SchrodingersGat** [comment]
The 10% recommendation comes from the IPC7351-C guidelines, but it doesn't work that well at smaller text sizes. I'll see if I can word it a bit better.

**Comment by Shackmeister** [comment]
@SchrodingersGat now its adjusting refdef size to the fab width on the angled
does it look good to you? 
pinheader_refdef

**Comment by SchrodingersGat** [comment]
The smaller texts are improved, but I would leave the larger ones as they were:

**Width**: 1.0mm
**Height**: 1.0mm
**Thickness**: 0.15mm

**Comment by poeschlr** [comment]
should we change the klc then to say approximately 15% textwidth instead of 10%

**Comment by Shackmeister** [comment]
changed the max size to 1.0 and thickness to 15%
skaermbillede fra 2017-06-28 14-43-38

**Comment by evanshultz** [comment]
@Shackmeister This is great! I had 3- and 4-row connectors on my list of things that were missing. Please let me know when you get around to that and I'll do the symbols. Thank you!

**Comment by Shackmeister** [comment]
@evanshultz thank you :) ill make the 3 and 4 columns as soon as I finish this :) if you want to help speed up you are welcome to give feedback on these as I go along :)

**Comment by Shackmeister** [comment]
@poeschlr @jkriege2 @evanshultz what fab style do you guys prefer for the angled Pin_Headers? I personally prefer the current but would very much like to know if @SchrodingersGat 's suggestion if more likeable for others

**Comment by SchrodingersGat** [comment]
`should we change the klc then to say approximately 15% textwidth instead of 10%`

I have updated the KLC for this.

**Comment by Shackmeister** [comment]
with some help from Jmwright (the author of CadQuery) and Maruice the Pinheader script can now generate all 500 models without crashing the computer :) meaning the 3d models are now ready for these footprints :) Also I have started working on the straight pinheaders
pinheader_3d

**Comment by evanshultz** [comment]
I ran a "pcb pin header right angle" Google search for images with the color green. The [search query is here](https://www.google.com/search?q=pcb+pin+header+right+angle&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjSttWwsOPUAhXFl5QKHQODC6YQ_AUICigB&biw=1920&bih=974#q=pcb+pin+header+right+angle&tbm=isch&tbs=ic:specific,isc:green). This reveals that, on a non-random sampling that should not be taken to correlate with any best practice or industry standard, that most right-angle pin headers don't have much silk. They may have fab layer drawings, though.

For me personally, I like the shape of the plastic holder and the pin area. I think having silk and fab lines there is useful. What is odd to me is having the fab text extend back over the pads. Typically one doesn't see that (FWIW) since the pad is typically understood to be connected to the other elements making up the footprint without this. Take a THT resistor footprint for an example:
image

The leads are shown in silk but not fab, and it's understood that even without showing the entire area the lead will take up on the board that there are leads which go all the way into the holes.

So, ultimately, my only suggestion would be removing or snipping back the fab line which are between the plastic and the pads. Perhaps just have them placed where silk is placed. This seems consistent with an obvious library footprint I thought to check and it also avoids having fab lines running over pads. Otherwise, this is amazing work @Shackmeister and I'm delighted to see such a vibrant community of folks volunteering their time to make KiCad great!

**Comment by Shackmeister** [comment]
Was also considering a seperate version of the right angled with no silkscreen for the pins (suggestion from my coleague)

**Comment by Shackmeister** [comment]
finished Straight Headers
please note the 2.54 has been made smaller for demonstration purposes on how the script handles the smaller body
please give comments to help me finish this :)
1_row
2_row

**Comment by Shackmeister** [comment]
@poeschlr @SchrodingersGat 
please have a look when you have time :)
also should we finish the discussion on the angled connector fab layer or should we merge them and open an issue to finish it up?

**Comment by evanshultz** [comment]
One idea about silk on the angled connectors: Instead of filling a huge rectangle of silk under the pin, what about making the small rectangle under the plastic body by pin 1 filled in? Then pin 1 is clearly marked in silk but it's covered up once the header is installed.

**Comment by Shackmeister** [comment]
@evanshultz im not sure I follow, can you please make a footprint screenshot  or use paint to draw one?

**Comment by evanshultz** [comment]
@Shackmeister Sorry for any confusion. I'm thinking something like this:
image

**Comment by Shackmeister** [comment]
That might make sense, but ill wait for other opinions before making the change :)

**Comment by poeschlr** [comment]
I would say during soldering the pin 1 marker is not really needed. 
(You can't solder in an angled connector in the wrong direction if you can see which direction the pins should go.) 

The reason why such a pin 1 marker might be useful is to aid the user who plugs in the mating connector. For that reason i think the original marking might be better. 
(The marker suggested by @evanshultz would not fulfill this purpose at all. I would rather remove this type of pin 1 mark completely than using one that vanishes below the part.)

**Comment by evanshultz** [comment]
@poeschlr Good point.

**Comment by Shackmeister** [comment]
@poeschlr makes perfect sense. So the main subject atm is the fab layer style. Personally i don't think it's too much, but would like the decision to be made by the more experienced librarians

**Comment by poeschlr** [comment]
I think your current version for the fab layer is more intuitive for beginners. Experienced users might prefer something like oliver suggested. I personally lean towards your current style.

**Comment by Shackmeister** [comment]
@poeschlr glad to know that. I just realised the SMD footprints doesn't keep the silkscreen out of the pads, ill fix that in a few days.. Any other comments to any of the footprints?

**Comment by poeschlr** [comment]
I think the footprints look ok. If you fix the silkscreen just give me a heads up.

**Comment by Shackmeister** [comment]
@poeschlr the script adds the lines for the Dual SMD packs as long as the distance is bigger than 2*silkscreen width. anything smaller simply looks like a dot.
this should also be the final fixes, so this should hopefully be the last needed for merge
smd dual row headers

**Comment by Shackmeister** [comment]
@SchrodingersGat @poeschlr can you guys please check if you have more things you would like to change? I believe it should be ready for merge now

**Comment by poeschlr** [comment]
Looks good.

**Comment by Shackmeister** [comment]
Great! Ill add the 960 3D files tomorrow :)

**Comment by SchrodingersGat** [comment]
Fantastic work here :) This is a serious improvement! Keep up the great work.

**Pull request merged**
