### PR TITLE
adding Pin header 1x02 Pitch3.96mm

### PR DESCRIPTION
**Pull request by ricardocrudo**

### CODE REVIEW

**Comment by michal777** [comment]
In line:
(module Pin_Header_Straight_1x02_Pitch3.96mm_Friction_Lock placed (layer F.Cu) (tedit 551D5BA6)
the word "placed" is not allowed in library.
Courtyard should be rounded to lay on 0.05 mm grid.
Silkscreen line should be 0.15 mm.
Reference and value should be as described in kicad library convention:

  (fp_text reference REF** (at 0 5.588) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value Pin_Header_Straight_1x02_Pitch3.96mm_Friction_Lock (at 5.1435 5.5245) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )

Some of the things that not match to KLC can be checked or fixed with my tool:
https://github.com/michal777/KiCad_Lib_Check
If you will try it please let me know if it works good.

**Comment by ricardocrudo** [comment]
>In line:
>(module Pin_Header_Straight_1x02_Pitch3.96mm_Friction_Lock placed (layer F.Cu) (tedit 551D5BA6)
>the word "placed" is not allowed in library.

hmm, I forked it from another footprint and this came as "inheritance". Fixed.

>3d model has no proper link (does it exist?).

It does. Soon I'll do a pull request with all  3dmodels that I have here. I'm waiting for a couple of merge that will happing with kicad-library. BTW, I do not have the wings files, are they required? 
In my '/usr/share/kicad/modules/packages3d' dir, the subdirectories don't have the suffix .3dshapes, should them have?

>Some of the things that not match to KLC can be checked or fixed with my tool:
>https://github.com/michal777/KiCad_Lib_Check
>If you will try it please let me know if it works good.

Cool! I've tried it and it works great. IMO, would be great if instead of receive the path via interactive way, it was via command line arguments. In this way the tests can be done more fast (up arrow + enter).

**Comment by ricardocrudo** [comment]
BTW, now with your script I'm reviewing all the other footprints that I've pushed.

**Comment by michal777** [comment]
.wings files are not necessary, .3dshapes suffix is required.
You won't be able to check Relay_DPDT_IM0(3,6,7)NS.kicad_mod because it contains: (), in name so some text fields in .kicad_mod are quoted and my tool will fail on it.

**Comment by michal777** [comment]
"placed" is still left. I didn't expect it so it's not fixed.

**Comment by CarlPoirier** [comment]
Thanks Ricardo.

**Pull request merged**
