### PR TITLE
changed to satisfy some KLC rules

### PR DESCRIPTION
**Pull request by michal777**
Rotated and moved, added courtyard, set positions of reference and value.

### CODE REVIEW

**Comment by kasbah** [comment]
You have two commits with the same commit message, you can squash them together with:

```bash
git clone git@github.com:michal777/Pin_Headers.pretty.git
cd Pin_Header.pretty
git reset ac16fa10
git commit -a --amend #you might want to capitalize the first letter as well at this point
git push -f
```

There is no need to close the pull-request, it will be updated.

**Comment by michal777** [comment]
Thanks, I fixed it.

**Comment by kasbah** [comment]
Ace :+1: ;)

Use `git push -f` very carefully in the future though, _especially_ if it is a repository others are contributing to.

**Comment by michal777** [comment]
Next change - 1-pin mark visible after assembly. Courtyard 0.5 mm.

**Pull request merged**
