### PR TITLE
adding 2x03 1.27mm pitch

### PR DESCRIPTION
**Pull request by kasbah**

### CODE REVIEW

**Comment by kasbah** [comment]
I checked this footprint with check_kicad_mod.py.

**Comment by pointhi** [comment]
please align the value text. The rest looks fine

**Comment by kasbah** [comment]
I amended the commit and moved the value text up a bit to match the other 1.27mm header footprints.

**Comment by pointhi** [comment]
Ok thanks,

there is one KLC issue remaining, because the courjard outline has to be 0.5mm for connectors. This was already wrong for the other ```1.27mm``` connectors.

**Comment by jkriege2** [comment]
this is available now!

**Pull request closed without merging**
