### PR TITLE
Added multiple footprints for 2mm headers (straight only)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Footprints downloaded from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm (shared under CC)
3D files (also downloaded from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm) have been added to:

https://github.com/KiCad/kicad-library

### CODE REVIEW

**Comment by ricardocrudo** [comment]
@SchrodingersGat name footprints following this standard: Pin_Header_Straight_1x01_Pitch1.00mm.kicad_mod

And mainly, footprints have to be in agreement with [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention). You can use [check_kicad_mod.py](https://github.com/KiCad/kicad-library-utils/tree/master/pcb) to help you.

**Comment by SchrodingersGat** [comment]
Names have been updated to match convention. Also the dimensions of text, line widths have been fixed. I have also renamed all the 3D files (which I'll commit to packages3D ASAP).

**Comment by ricardocrudo** [comment]
Hello @SchrodingersGat 

The footprints still having some issues:
* Silkscreen is superposing pads
* Courtyard line is missing
* Anchor is not set at pin 1

Also would be nice if the silkscreen look like with already existing ones.

Thanks

**Comment by SchrodingersGat** [comment]
These changes have been made to the 2.00mm pitch pin-headers @ricardocrudo

**Comment by CarlPoirier** [comment]
Hi Oliver,

The courtyard is missing for the Pin_Header_Straight_1x02_Pitch2.00mm. Also, for the 2-pin wide headers, the holes are not centered with the pads. Is this wanted?

**Comment by SchrodingersGat** [comment]
Hi Carl,

I've added a courtyard to the footprint in question.

Regarding the non-centered holes - this is how these footprints were "supplied" from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm

Do you think they would be better served by smaller, centered pads?

**Comment by CarlPoirier** [comment]
Hi Oliver,

The courtyard clearance for connectors should be 0.5mm as per rule 6.7. Besides that, the silkscreen does not allow one to determine the pin one position once the connector has been soldered on it. That would be great to fix as well. As for the pads, maybe it would be better to have them centered like the rest of the library. Besides that, it will be a great addition to the library!

**Comment by SchrodingersGat** [comment]
Hey @CarlPoirier - I have completely re-made these footprints. The ones supplied from smisioto were OK but getting them to KLC was too difficult. In the end I just re-scripted the whole thing.

They are passing KLC and I have designed to match the current pin-headers as much as possible.

Please let me know if there are any more changes I can make to these.

**Comment by SchrodingersGat** [comment]
@CarlPoirier I have also added the 3D models back in.

The 3D models for the 2.00mm pin headers are here:

https://github.com/KiCad/kicad-library/pull/400

**Comment by SchrodingersGat** [comment]
@ricardocrudo these have been re-generated and changed to match the 2.54mm pin headers

**Comment by SchrodingersGat** [comment]
@CarlPoirier in addition to these 2.00mm headers, I have generated 3D models (STEP and WRL pairs) for these and the 2.54mm straight pin headers)

See: https://github.com/SchrodingersGat/kicad-packages3d/tree/master/Pin_Headers.3dshapes

The STEP and WRL pairs allow for use with tools such as StepUp.

**Comment by SchrodingersGat** [comment]
headers

Example:

**Comment by SchrodingersGat** [comment]
I'm closing this one to start afresh (so that I'm not pushing from my master branch).

New PR - https://github.com/KiCad/Pin_Headers.pretty/pull/13

**Pull request closed without merging**
