### PR TITLE
added Pin_Headers mounted as SMD-parts

### PR DESCRIPTION
**Pull request by jkriege2**
as discussed in https://github.com/KiCad/Connectors_Samtec.pretty/pull/4 I created a set of pinheaders mounted as SMD parts. This is a full set with two pin-orderings for 1-column headers + 2-column-headers. Also all pitches are available, i.e. 1.27mm, 2.00mm and 2.54mm.

script-based: https://github.com/pointhi/kicad-footprint-generator/pull/18

datasheets:
- http://www.conexcon.com/PDF/2590.pdf
- http://katalog.we-online.de/em/datasheet/6100xx21121.pdf
- http://katalog.we-online.de/em/datasheet/6210xx245821.pdf
- https://www.hirose.co.kr/Upload/Product/Catalog/e62103032.pdf

2017-01-24 22_27_04-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
2017-01-24 22_31_48-3d viewer
2017-01-24 22_51_04-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb

### CODE REVIEW

**Comment by Frankkkkk** [comment]
I think that **xxx_SMD_L** and **xxx_SMD_R** is more "logical" than **style1** or **style2**.

But apart from that, I'm 100% for it !

Thanks; it's indeed better and fuller than what I did ;-).

**Comment by jkriege2** [comment]
I chose a slightly different naming scheme that is more graphic (IMHO):
- `_Pin1Left`
- `_Pin1Right`

JAN

**Comment by Frankkkkk** [comment]
Seems good to me ;-)

**Comment by jkriege2** [comment]
@SchrodingersGat could you have a look?

**Comment by SchrodingersGat** [comment]
Also seems good to me. 

I will merge this but take note that now a footprint from this library looks like:

`Pin_Headers.pretty:Pin_Header_Straight_1x34_Pitch2.00mm_SMD_Pin1Right` which is getting very long.

Ideally, I would like to remove the duplicate `Pin_Header_` at the start of the filename, but that requires some changes to the way that footprint filtering works, so we'll leave it for now.

Thanks for the contribution.

**Pull request merged**
