### PR TITLE
added pin-header symbols for 3-pin and 4-pin Fan connectors, as used on PC mainboards

### PR DESCRIPTION
**Pull request by jkriege2**
3pin
4pin

### CODE REVIEW

**Comment by jkriege2** [comment]
see http://www.formfactors.org/developer%5Cspecs%5Crev1_2_public.pdf for details on the 4-pin package

**Comment by jkriege2** [comment]
I aso added a motors symbol library, which uses these footprints: https://github.com/KiCad/kicad-library/pull/703

**Comment by jkriege2** [comment]
should conform now to KLC
for 3D models see: https://github.com/KiCad/kicad-library/pull/725

**Comment by pointhi** [comment]
I think https://github.com/KiCad/Connect.pretty is a better place for this Pull Request

**Comment by jkriege2** [comment]
OK, I created a new PR there:
https://github.com/KiCad/Connect.pretty/pull/43

**Pull request closed without merging**
